name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: |
          REPO_NAME="${{ github.repository }}"
          ARRAY=(${REPO_NAME//\// })
          DIR_NAME=${ARRAY[1]}
          cd $DIR_NAME
          pwd
      - name: Build
        run: |
          pwd
      - run: echo "deploy"
