name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }} .
      - name: Check out branch
        run: |
          GITHUB_REF="${{ github.ref }}"
          ARRAY=(${GITHUB_REF//\// })
          BRANCH_NAME=${ARRAY[2]}
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ $BRANCH_NAME != $CURRENT_BRANCH ]; then
            echo "Start to fetch origin/$BRANCH_NAME"
            git fetch origin $BRANCH_NAME
            git checkout $BRANCH_NAME
          else
            echo "Current branch is $CURRENT_BRANCH."
          fi
      - name: Build
        run: |
          echo $(git rev-parse --abbrev-ref HEAD)
          echo "Build"
      - name: Setup ssh
        run: |
          SSHPATH="$HOME/.ssh"
          if [ ! -d "$SSHPATH" ]
          then
            mkdir $SSHPATH
          fi
          if [ ! -f "$SSHPATH/known_hosts" ]
          then
            touch $SSHPATH/known_hosts
          fi
          chmod 700 $SSHPATH
          chmod 600 $SSHPATH/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $SSHPATH/id_rsa
          chmod 600 $SSHPATH/id_rsa
          ssh-keygen -y -t rsa -f $SSHPATH/id_rsa
      - name: Update server
      	run: |
          echo "
            echo \"docker-compose build ...\" >> /home/github-action-build.log
          " | ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}